name: ui_components
description: "Reusable UI components for task management app"
version: 1.0.0

environment:
  sdk: '>=3.7.2 <4.0.0'  # 範囲指定に変更（^3.7.2 → '>=3.7.2 <4.0.0'）
  flutter: ">=3.0.0"     # より適切なバージョンに調整

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter: